### PR TITLE
fix: scrape the right page

### LINKED ISSUE #132: Just few Updates
heyho,

I noticed that there was an error in the code with #129.
Since this update, only the baseUrl is queried, but not the individual pages.

This probably happened because the code line 
`const html = await (await fetch(baseUrl)).text();`
was replaced everywhere by the #fetch function, which does not take any parameters but always retrieves the baseUrl.
`const html = await this.#fetch();`

https://github.com/WFCD/warframe-patchlogs/blob/21da197b829c89d1c79a5198a710cc426ad2551c/build/scraper.js#L22-L24

`build/scraper.js L21-L33`
```diff
  async getPageNumbers() {
+   const html = await this.#fetch();
-   const html = await (await fetch(baseUrl)).text();
    const $ = cheerio.load(html);
```

`build/scraper.js L48-L50`
```diff
  async scrape(url, bar) {
+   const html = await this.#fetch();
-   const html = await (await fetch(baseUrl)).text();
    const $ = cheerio.load(html);
```

`build/scraper.js L97-L99`
```diff
  async scrapePost(url, data) {
+   const html = await this.#fetch();
-   const html = await (await fetch(baseUrl)).text();
    const $ = cheerio.load(html);
```

### PR DESCRIPTION
**Pull request by monster010**
### What did you fix?
Fixing only the first page get scraped

closes #132 

---

### Reproduction steps

---

### Evidence/screenshot/link to line

https://github.com/WFCD/warframe-patchlogs/blob/dd2e6cdc0d83884c353b4aadd04ae87974562bd3/build/scraper.js#L22-L24
https://github.com/WFCD/warframe-patchlogs/blob/dd2e6cdc0d83884c353b4aadd04ae87974562bd3/build/scraper.js#L31-L33
https://github.com/WFCD/warframe-patchlogs/blob/dd2e6cdc0d83884c353b4aadd04ae87974562bd3/build/scraper.js#L48-L50
https://github.com/WFCD/warframe-patchlogs/blob/dd2e6cdc0d83884c353b4aadd04ae87974562bd3/build/scraper.js#L97-L99

### Considerations
- Does this contain a new dependency? **[Yes/No]**
- Does this introduce opinionated data formatting or manual data entry? **[Yes/No]**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes/No]**
- Have I run the linter? **[Yes/No]**
- Is is a bug fix, feature request, or enhancement? **[Bug Fix/Feature/Enhancement/Docs/Maintenance]**

### CODE REVIEW

File: build/scraper.js [hunk 1]
```diff
@@ -19,8 +19,8 @@ class Scraper {
     this.posts = [];
   }
 
-  async #fetch() {
-    return (await fetch(baseUrl)).text();
+  async #fetch(url) {
```
Comment (TobiTenno) [inline build/scraper.js:22]:
```suggestion
  async #fetch(url = baseUrl) {
```

File: build/scraper.js [hunk 2]
```diff
@@ -29,7 +29,7 @@ class Scraper {
    * @returns {Promise<number>} total number of pages
    */
   async getPageNumbers() {
-    const html = await this.#fetch();
+    const html = await this.#fetch(baseUrl);
```
Comment (TobiTenno) [inline build/scraper.js:32]:
```suggestion
    const html = await this.#fetch();
```

File: build/scraper.js (hunk 1 above)
Comment (TobiTenno) [inline build/scraper.js:22]:
```suggestion
  async #fetch(url = baseUrl) {
```

File: build/scraper.js (hunk 2 above)
Comment (TobiTenno) [inline build/scraper.js:32]:
```suggestion
    const html = await this.#fetch();
```

**Review by TobiTenno — CHANGES_REQUESTED** [review]
default to the base url first... otherwise, you're obviously spot-on

**Comment by TobiTenno** [comment]
i'm thinking this might require spacing the requests artificially to avoid the cloudflare bypasses

**Comment by TobiTenno** [comment]
well, not _this_, just but my missing of this scenario

**Comment by TobiTenno** [comment]
i'll see if this can work, otherwise, i'll probably go add the cloudflare-promise code back (probably necessary 😢)

**Comment by monster010** [comment]
It works, i tryed it from my PC, but i dont know how offen u let run it.

**Comment by TobiTenno** [comment]
yeah, the problem isn't locally, generally, but on CI servers, like GH actions here.

**Comment by TobiTenno** [comment]
yeah, the problem isn't locally, generally, but on CI servers, like GH actions here.
